# Generated by Django 4.2.2 on 2025-09-18 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('inicio', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_titular', models.CharField(max_length=30)),
                ('nome_conjuge', models.CharField(max_length=30)),
                ('data_nascimento', models.DateField()),
                ('data_inicio', models.DateField()),
                ('cpf', models.CharField(max_length=30)),
                ('contato', models.CharField(max_length=30)),
                ('bpc', models.CharField(max_length=50)),
                ('nis', models.CharField(max_length=50)),
                ('dap', models.CharField(max_length=50)),
                ('aposentadoria', models.BooleanField(default=False)),
                ('auxilio', models.BooleanField(default=False)),
                ('escolaridade', models.IntegerField(choices=[(1, 'nenhum'), (2, 'fundamental incompleto'), (3, 'fundamental completo'), (4, 'ensino médio incompleto'), (5, 'ensino médio completo'), (6, 'ensino superior incompleto'), (7, 'ensino superior completo'), (8, 'pós-graduação')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Subsystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_subsistema', models.CharField(max_length=50)),
                ('produtos_base', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tecnico', models.CharField(max_length=30)),
                ('descricao', models.TextField()),
                ('telefone', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=30)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('comunidade', models.CharField(max_length=30, null=True)),
                ('tamanho_m2', models.FloatField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('senha', models.CharField(max_length=200)),
                ('contato', models.CharField(max_length=30)),
                ('foto_perfil', models.ImageField(blank=True, upload_to='fotos_perfil/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_projeto', models.CharField(max_length=30)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('orcamento', models.CharField(blank=True, max_length=30, null=True)),
                ('familias', models.ManyToManyField(to='seapac.family')),
                ('tecnicos', models.ManyToManyField(to='seapac.tecnicos')),
            ],
        ),
        migrations.CreateModel(
            name='FamilySubsystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produtos_saida', models.JSONField(blank=True, default=list)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seapac.family')),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seapac.subsystem')),
            ],
            options={
                'unique_together': {('family', 'subsystem')},
            },
        ),
        migrations.AddField(
            model_name='family',
            name='projeto',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='seapac.project'),
        ),
        migrations.AddField(
            model_name='family',
            name='subsistemas',
            field=models.ManyToManyField(blank=True, through='seapac.FamilySubsystem', to='seapac.subsystem'),
        ),
        migrations.AddField(
            model_name='family',
            name='terra',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='seapac.terrain'),
        ),
    ]
