# Generated by Django 4.2.2 on 2025-07-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seapac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_subsistema', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='family',
            name='aposentadoria',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='auxilio',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='bpc',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='contato',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='cpf',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='dap',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='data_inic',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='data_nasc',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='escolaridade',
            field=models.CharField(choices=[('1', 'nenhum'), ('2', 'fundamental incompleto'), ('3', 'fundamental completo'), ('4', 'ensino médio incompleto'), ('5', 'ensino médio completo'), ('6', 'ensino superior incompleto'), ('7', 'ensino superior completo'), ('8', 'pós-graduação')], default='1', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='nis',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='nome_conjuge',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='nome_familia',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='contato',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
        migrations.AddField(
            model_name='user',
            name='senha',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='nome_titular',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nome',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
