# Generated by Django 4.2.2 on 2025-09-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seapac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsystem',
            name='produtos_base',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
