# Generated by Django 4.2.2 on 2025-08-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seapac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsystem',
            name='produtos_entrada_opcoes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subsystem',
            name='produtos_saida_opcoes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
