# Generated by Django 4.2.2 on 2025-08-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seapac', '0002_subsystem_produtos_entrada_opcoes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsystem',
            name='destino_produtos_entrada',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subsystem',
            name='destino_produtos_saida',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subsystem',
            name='produtos_entrada',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subsystem',
            name='produtos_saida',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
