# Generated by Django 4.2.2 on 2025-08-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seapac', '0003_alter_subsystem_destino_produtos_entrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
    ]
