# Generated by Django 4.2.2 on 2025-07-14 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seapac', '0003_block_connection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='source',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='target',
        ),
        migrations.DeleteModel(
            name='Block',
        ),
        migrations.DeleteModel(
            name='Connection',
        ),
    ]
