# Generated by Django 4.2.2 on 2025-08-12 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seapac', '0004_alter_project_data_fim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='nivel',
            field=models.IntegerField(choices=[(1, 'Inicial'), (2, 'Intermediario'), (3, 'Avancado')], default=1),
        ),
    ]
