# Generated by Django 4.2.2 on 2025-07-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seapac', '0004_remove_connection_source_remove_connection_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='nivel',
            field=models.CharField(choices=[('1', 'baixo'), ('2', 'intermediário'), ('3', 'avançado')], default='1', max_length=30, null=True),
        ),
    ]
