# Generated by Django 4.2.2 on 2025-07-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seapac', '0005_family_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='escolaridade',
            field=models.IntegerField(choices=[(1, 'nenhum'), (2, 'fundamental incompleto'), (3, 'fundamental completo'), (4, 'ensino médio incompleto'), (5, 'ensino médio completo'), (6, 'ensino superior incompleto'), (7, 'ensino superior completo'), (8, 'pós-graduação')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='nivel',
            field=models.IntegerField(choices=[(1, 'baixo'), (2, 'intermediário'), (3, 'avançado')], default=1, null=True),
        ),
    ]
