# Generated by Django 4.2.2 on 2025-08-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seapac', '0005_alter_family_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='data_nascimento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='family',
            name='nivel',
            field=models.IntegerField(blank=True, choices=[(1, 'Inicial'), (2, 'Intermediario'), (3, 'Avancado')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='subsistemas',
            field=models.ManyToManyField(blank=True, null=True, to='seapac.subsystem'),
        ),
    ]
