# Generated by Django 4.2.2 on 2025-08-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seapac', '0006_alter_family_data_nascimento_alter_family_nivel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='subsistemas',
            field=models.ManyToManyField(blank=True, to='seapac.subsystem'),
        ),
    ]
