# Generated by Django 4.2.2 on 2025-07-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seapac', '0006_alter_family_escolaridade_alter_family_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='nivel',
            field=models.IntegerField(choices=[(1, 'Baixo'), (2, 'Intermediário'), (3, 'Avançado')], default=1, null=True),
        ),
    ]
