# Generated by Django 4.2.2 on 2025-08-16 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seapac', '0007_alter_family_subsistemas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='nivel',
        ),
    ]
