# Generated by Django 5.2.5 on 2025-09-16 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seapac', '0008_remove_family_nivel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tecnico', models.CharField(max_length=30)),
                ('descricao', models.TextField()),
                ('telefone', models.CharField()),
                ('cpf', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, upload_to='fotos_perfil/')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='familias',
            field=models.ManyToManyField(to='seapac.family'),
        ),
        migrations.AddField(
            model_name='project',
            name='orcamento',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tecnicos',
            field=models.ManyToManyField(to='seapac.tecnicos'),
        ),
    ]
