# Generated by Django 4.2.2 on 2025-09-08 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seapac', '0008_remove_family_nivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsystem',
            name='destino_produtos_entrada',
        ),
        migrations.RemoveField(
            model_name='subsystem',
            name='destino_produtos_saida',
        ),
        migrations.RemoveField(
            model_name='subsystem',
            name='produtos_entrada',
        ),
        migrations.RemoveField(
            model_name='subsystem',
            name='produtos_entrada_opcoes',
        ),
        migrations.RemoveField(
            model_name='subsystem',
            name='produtos_saida',
        ),
        migrations.RemoveField(
            model_name='subsystem',
            name='produtos_saida_opcoes',
        ),
        migrations.CreateModel(
            name='ProdutoSaida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('porcentagem', models.DecimalField(decimal_places=2, max_digits=5)),
                ('destino', models.CharField(max_length=100)),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_saida', to='seapac.subsystem')),
            ],
        ),
    ]
