# Generated by Django 4.2.2 on 2025-08-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seapac', '0008_alter_family_nivel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('inicio', models.DateTimeField()),
            ],
        ),
    ]
