# Generated by Django 4.2.2 on 2025-09-08 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seapac', '0009_remove_subsystem_destino_produtos_entrada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtosaida',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='produtosaida',
            name='porcentagem',
        ),
        migrations.RemoveField(
            model_name='subsystem',
            name='foto_subsistema',
        ),
        migrations.AlterField(
            model_name='produtosaida',
            name='subsystem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='seapac.subsystem'),
        ),
        migrations.AlterField(
            model_name='subsystem',
            name='nome_subsistema',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Fluxo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(blank=True, max_length=100, null=True)),
                ('porcentagem', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fluxos', to='seapac.produtosaida')),
            ],
        ),
    ]
