# Generated by Django 5.2.5 on 2025-09-16 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seapac', '0009_tecnicos_project_familias_project_orcamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tecnicos',
            name='foto',
        ),
    ]
