# Generated by Django 4.2.2 on 2025-08-01 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seapac', '0009_visita'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Visita',
            new_name='Evento',
        ),
    ]
