# Generated by Django 5.2.5 on 2025-09-16 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seapac', '0010_remove_tecnicos_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='projeto',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='seapac.project'),
        ),
    ]
