# Generated by Django 4.2.2 on 2025-09-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seapac', '0010_remove_produtosaida_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsystem',
            name='produtos_saida',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
