# Generated by Django 4.2.2 on 2025-08-01 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seapac', '0010_rename_visita_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_visita', models.DateTimeField()),
                ('observacoes', models.TextField(blank=True)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seapac.family')),
            ],
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
    ]
