# Generated by Django 4.2.2 on 2025-09-09 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seapac', '0011_subsystem_produtos_saida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtosaida',
            name='subsystem',
        ),
        migrations.DeleteModel(
            name='Fluxo',
        ),
        migrations.DeleteModel(
            name='ProdutoSaida',
        ),
    ]
