# Generated by Django 4.2.2 on 2025-08-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seapac', '0011_visita_delete_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('inicio', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Visita',
        ),
    ]
