# Generated by Django 4.2.2 on 2025-07-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0002_subsystem_family_aposentadoria_family_auxilio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subsystem',
            old_name='nome_sistema',
            new_name='nome_subsistema',
        ),
        migrations.AlterField(
            model_name='user',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
    ]
